apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
  namespace: xogame
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379