apiVersion: apps/v1
kind: Deployment
metadata:
  name: xogame
  namespace: xogame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xogame
  template:
    metadata:
      labels:
        app: xogame
    spec:
      containers:
      - name: xogame
        image: gidyon/xo:v1.6
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: TLS_CERT_FILE
          value: /certs/cert.pem
        - name: TLS_KEY_FILE
          value: /certs/key.pem
        volumeMounts:
        - name: app-tls
          mountPath: /certs/
          readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: xogame-tls
