apiVersion: v1
kind: Service
metadata:
  name: xogame
  namespace: xogame
  labels:
    app: xogame
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 443
    protocol: TCP
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    app: xogame